version: '3.8'

services:
  frontend:
    build:
      context: ./client
    environment:
      VITE_API_BASE_URL: http://api:4000
    ports:
      - "${FRONTEND_PORT:-8123}:8123"
    depends_on:
      - api
  api:
    build:
      context: ./server
    env_file:
      - ./server/.env
    environment:
      STATIC_MAP_DIRECTORIES: /app/maps
    volumes:
      - ./server/maps:/app/maps
    ports:
      - "4000:4000"
    depends_on:
      - postgres
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-comutiny}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
