version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:2567
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    command: ["npm", "run", "dev"]
    ports:
      - "2567:2567"
    environment:
      - DATABASE_URL=postgres://comutiny:comutiny@postgres:5432/comutiny
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./backend:/app
      - backend-node-modules:/app/node_modules
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: comutiny
      POSTGRES_PASSWORD: comutiny
      POSTGRES_DB: comutiny
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  frontend-node-modules:
  backend-node-modules:
  postgres-data:
  redis-data:
