version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: app-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://app_user:app_password@postgres:5432/app_db
      APP_ENV: development
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    environment:
      API_URL: http://backend:8000
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

volumes:
  postgres-data:
