version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - '2567:2567'
    environment:
      - NODE_ENV=production
